---
variables:
  LANG: 'en_US.UTF-8'
  LC_ALL: 'en_US.UTF-8'
  LANGUAGE: 'en_US.UTF-8'

image: debian:stretch
stages:
  - build
  - tests
  - lint


build:
  stage: build
  script:
  - apt-get -qq update
  - DEBIAN_FRONTEND=noninteractive apt-get -qq install -y locales
  - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && dpkg-reconfigure --frontend=noninteractive locales && update-locale LANG=en_US.UTF-8
  - ./install_re2o.sh ci-setup
  - cat re2o/settings_local.py


lint:
  stage: lint
  script:
  - apt-get -qq update
  - DEBIAN_FRONTEND=noninteractive apt-get -qq install -y locales
  - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && dpkg-reconfigure --frontend=noninteractive locales && update-locale LANG=en_US.UTF-8
  - ./install_re2o.sh ci-setup
  - pylint3 --load-plugins pylint_django cotisations machines re2o logs topologie preferences search users || if [ $? -ne 1 ]; then exit 0; else exit 1; fi


tests:
  stage: tests
  script:
  - apt-get -qq update
  - DEBIAN_FRONTEND=noninteractive apt-get -qq install -y locales
  - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && dpkg-reconfigure --frontend=noninteractive locales && update-locale LANG=en_US.UTF-8
  - ./install_re2o.sh ci-setup
  - python3 manage.py test
