---
image: debian:buster
stages:
  - deploy_doc
  - lint

lint:
  stage: lint
  variables:
    LANG: 'en_US.UTF-8'
    LC_ALL: 'en_US.UTF-8'
    LANGUAGE: 'en_US.UTF-8'
  script:
  - apt-get -qq update
  - DEBIAN_FRONTEND=noninteractive apt-get -qq install -y locales python3-django python3-pylint-django
  - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && dpkg-reconfigure --frontend=noninteractive locales && update-locale LANG=en_US.UTF-8
  - pylint3 --load-plugins pylint_django cotisations machines re2o logs topologie preferences search users || if [ $? -ne 1 ]; then exit 0; else exit 1; fi

pages:
  stage: deploy_doc
  script:
    - apt-get -qq update
    - cat apt_requirements.txt | grep python3 | xargs apt-get -qq install -y
    - python3 -m pip install -U -r pip_requirements.txt
    - python3 -m pip install -U sphinx recommonmark
    - cp re2o/settings_local.example.py re2o/settings_local.py
    - sed -i 's/MY_EMAIL_PORT/25/g' re2o/settings_local.py
    - apt-get -y install python3-mysqldb default-mysql-client
    - sed -i 's/db_engine/django.db.backends.mysql/g' re2o/settings_local.py
    - sphinx-apidoc -o re2o/docs_utils/source/autodoc/ -f . ./*/migrations/*
    - sphinx-build -b html docs_utils/source/ public
  artifacts:
    paths:
      - public


